### ISSUE TITLE
Version number wrong in clamp.js file?

### ISSUE THREAD

**Issue by picobots** [jmenglis/clamp-js-main#15]
I just want to make sure that I'm using the most recent version of this library. It looks like `0.11.5` is the latest version, but the comment at the top of https://github.com/jmenglis/clamp-js-main/blob/master/clamp.js says `0.11.4`. Is the version just wrong in the comment, or is that file actually an older version?

**Comment by jmenglis** [comment]
Fixed with merge of #14
